name: CI/CD Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Build backend
        run: docker build -t api-service ./api-service

      - name: Build frontend
        run: docker build -t web-client ./web-client